mobile.payment.host=https://api.payments.bbva
safetynet.key=AIzaSyBXhuFMyDFQgv-0ChSv4Ejl1OPRx3YX1ao
overwrite_cdcvm_with_online_pin=false
visa.bullet.ttl_in_seconds=2592000
scheduler.get_token_task.initial_delay_in_seconds=20
scheduler.get_token_task.max_time_in_seconds=80
lock.max_time_in_mills=45000
jca.provider=SC
cdcvmSupported=true
armadillo.auth.basic=Basic MTAwMDAxODc6OUNQdFhKdE4kNVFoelcyRVZARW5udU40ZmM0cDJyTlJkQjlIY2J5VCRDRTVjZiNqazgzcGNkdSNSd29MQmIkWA==
mobile.payment.armadillo.path.url=/auth/token?grant_type=pkcs7
mobile.payment.armadillo.base.url=https://api.payments.bbva
userAuthenticationTtlInSeconds=20
mobile.payment.kmconfig=TOHU_PRO
broadcast.receiver.package=com.bancomer.mbanking
broadcast.receiver.class=com.bbva.bgm.contactlesspaymentui.receivers.MobilePaymentBroadcastReceiver
