gp2.base.url=https://api.payments.bbva
safetynet.apikey=AIzaSyBXhuFMyDFQgv-0ChSv4Ejl1OPRx3YX1ao
gp2.preregister.url=/hub/v2/preRegister
gp2.setpushtoken.url=/hub/v2/setPushToken
gp2.kmconfig=TOHU_PRO
gp2.armadillo.auth.basic=Basic MTAwMDAxODc6OUNQdFhKdE4kNVFoelcyRVZARW5udU40ZmM0cDJyTlJkQjlIY2J5VCRDRTVjZiNqazgzcGNkdSNSd29MQmIkWA==
gp2.armadillo.url=/auth/token?grant_type=pkcs7
country.code=mx
country.name=Mexico
